kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/crcresearch/vuetify-cc

steps:
  - name: publish  
    image: plugins/docker
    environment:
      VUE_APP_AXIOS_BASE_URL:
        from_secret: VUE_APP_AXIOS_BASE_URL
      VUE_APP_GRANT_TYPE:
        from_secret: VUE_APP_GRANT_TYPE
      VUE_APP_CLIENT_ID:
        from_secret: VUE_APP_CLIENT_ID
      VUE_APP_CLIENT_SECRET:
        from_secret: VUE_APP_CLIENT_SECRET
    settings:
      build_args_from_env:
        - VUE_APP_AXIOS_BASE_URL
        - VUE_APP_GRANT_TYPE
        - VUE_APP_CLIENT_ID
        - VUE_APP_CLIENT_SECRET
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD
      repo: zazu.crc.nd.edu/cookiecutters/vuetify-cc
      registry: zazu.crc.nd.edu
      tags:
       - latest
       - '1.0'